// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ContactsColumns holds the columns for the "contacts" table.
	ContactsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeUint32},
		{Name: "updated_at", Type: field.TypeUint32},
		{Name: "deleted_at", Type: field.TypeUint32},
		{Name: "app_id", Type: field.TypeUUID},
		{Name: "used_for", Type: field.TypeString},
		{Name: "sender", Type: field.TypeString, Default: ""},
		{Name: "account", Type: field.TypeString, Default: ""},
		{Name: "account_type", Type: field.TypeString, Default: ""},
	}
	// ContactsTable holds the schema information for the "contacts" table.
	ContactsTable = &schema.Table{
		Name:       "contacts",
		Columns:    ContactsColumns,
		PrimaryKey: []*schema.Column{ContactsColumns[0]},
	}
	// EmailTemplatesColumns holds the columns for the "email_templates" table.
	EmailTemplatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeUint32},
		{Name: "updated_at", Type: field.TypeUint32},
		{Name: "deleted_at", Type: field.TypeUint32},
		{Name: "app_id", Type: field.TypeUUID},
		{Name: "lang_id", Type: field.TypeUUID},
		{Name: "default_to_username", Type: field.TypeString},
		{Name: "used_for", Type: field.TypeString},
		{Name: "sender", Type: field.TypeString},
		{Name: "reply_tos", Type: field.TypeJSON},
		{Name: "cc_tos", Type: field.TypeJSON},
		{Name: "subject", Type: field.TypeString, Default: ""},
		{Name: "body", Type: field.TypeString, Size: 8192, Default: ""},
	}
	// EmailTemplatesTable holds the schema information for the "email_templates" table.
	EmailTemplatesTable = &schema.Table{
		Name:       "email_templates",
		Columns:    EmailTemplatesColumns,
		PrimaryKey: []*schema.Column{EmailTemplatesColumns[0]},
	}
	// SmsTemplatesColumns holds the columns for the "sms_templates" table.
	SmsTemplatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeUint32},
		{Name: "updated_at", Type: field.TypeUint32},
		{Name: "deleted_at", Type: field.TypeUint32},
		{Name: "app_id", Type: field.TypeUUID},
		{Name: "lang_id", Type: field.TypeUUID},
		{Name: "used_for", Type: field.TypeString, Default: ""},
		{Name: "subject", Type: field.TypeString, Default: ""},
		{Name: "message", Type: field.TypeString, Default: ""},
	}
	// SmsTemplatesTable holds the schema information for the "sms_templates" table.
	SmsTemplatesTable = &schema.Table{
		Name:       "sms_templates",
		Columns:    SmsTemplatesColumns,
		PrimaryKey: []*schema.Column{SmsTemplatesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ContactsTable,
		EmailTemplatesTable,
		SmsTemplatesTable,
	}
)

func init() {
}
