// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/third-manager/pkg/db/ent/appemailtemplate"
	"github.com/NpoolPlatform/third-manager/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// AppEmailTemplateUpdate is the builder for updating AppEmailTemplate entities.
type AppEmailTemplateUpdate struct {
	config
	hooks     []Hook
	mutation  *AppEmailTemplateMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the AppEmailTemplateUpdate builder.
func (aetu *AppEmailTemplateUpdate) Where(ps ...predicate.AppEmailTemplate) *AppEmailTemplateUpdate {
	aetu.mutation.Where(ps...)
	return aetu
}

// SetCreatedAt sets the "created_at" field.
func (aetu *AppEmailTemplateUpdate) SetCreatedAt(u uint32) *AppEmailTemplateUpdate {
	aetu.mutation.ResetCreatedAt()
	aetu.mutation.SetCreatedAt(u)
	return aetu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (aetu *AppEmailTemplateUpdate) SetNillableCreatedAt(u *uint32) *AppEmailTemplateUpdate {
	if u != nil {
		aetu.SetCreatedAt(*u)
	}
	return aetu
}

// AddCreatedAt adds u to the "created_at" field.
func (aetu *AppEmailTemplateUpdate) AddCreatedAt(u int32) *AppEmailTemplateUpdate {
	aetu.mutation.AddCreatedAt(u)
	return aetu
}

// SetUpdatedAt sets the "updated_at" field.
func (aetu *AppEmailTemplateUpdate) SetUpdatedAt(u uint32) *AppEmailTemplateUpdate {
	aetu.mutation.ResetUpdatedAt()
	aetu.mutation.SetUpdatedAt(u)
	return aetu
}

// AddUpdatedAt adds u to the "updated_at" field.
func (aetu *AppEmailTemplateUpdate) AddUpdatedAt(u int32) *AppEmailTemplateUpdate {
	aetu.mutation.AddUpdatedAt(u)
	return aetu
}

// SetDeletedAt sets the "deleted_at" field.
func (aetu *AppEmailTemplateUpdate) SetDeletedAt(u uint32) *AppEmailTemplateUpdate {
	aetu.mutation.ResetDeletedAt()
	aetu.mutation.SetDeletedAt(u)
	return aetu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (aetu *AppEmailTemplateUpdate) SetNillableDeletedAt(u *uint32) *AppEmailTemplateUpdate {
	if u != nil {
		aetu.SetDeletedAt(*u)
	}
	return aetu
}

// AddDeletedAt adds u to the "deleted_at" field.
func (aetu *AppEmailTemplateUpdate) AddDeletedAt(u int32) *AppEmailTemplateUpdate {
	aetu.mutation.AddDeletedAt(u)
	return aetu
}

// SetAppID sets the "app_id" field.
func (aetu *AppEmailTemplateUpdate) SetAppID(u uuid.UUID) *AppEmailTemplateUpdate {
	aetu.mutation.SetAppID(u)
	return aetu
}

// SetLangID sets the "lang_id" field.
func (aetu *AppEmailTemplateUpdate) SetLangID(u uuid.UUID) *AppEmailTemplateUpdate {
	aetu.mutation.SetLangID(u)
	return aetu
}

// SetDefaultToUsername sets the "default_to_username" field.
func (aetu *AppEmailTemplateUpdate) SetDefaultToUsername(s string) *AppEmailTemplateUpdate {
	aetu.mutation.SetDefaultToUsername(s)
	return aetu
}

// SetUsedFor sets the "used_for" field.
func (aetu *AppEmailTemplateUpdate) SetUsedFor(s string) *AppEmailTemplateUpdate {
	aetu.mutation.SetUsedFor(s)
	return aetu
}

// SetSender sets the "sender" field.
func (aetu *AppEmailTemplateUpdate) SetSender(s string) *AppEmailTemplateUpdate {
	aetu.mutation.SetSender(s)
	return aetu
}

// SetReplyTos sets the "reply_tos" field.
func (aetu *AppEmailTemplateUpdate) SetReplyTos(s []string) *AppEmailTemplateUpdate {
	aetu.mutation.SetReplyTos(s)
	return aetu
}

// SetCcTos sets the "cc_tos" field.
func (aetu *AppEmailTemplateUpdate) SetCcTos(s []string) *AppEmailTemplateUpdate {
	aetu.mutation.SetCcTos(s)
	return aetu
}

// SetSubject sets the "subject" field.
func (aetu *AppEmailTemplateUpdate) SetSubject(s string) *AppEmailTemplateUpdate {
	aetu.mutation.SetSubject(s)
	return aetu
}

// SetBody sets the "body" field.
func (aetu *AppEmailTemplateUpdate) SetBody(s string) *AppEmailTemplateUpdate {
	aetu.mutation.SetBody(s)
	return aetu
}

// Mutation returns the AppEmailTemplateMutation object of the builder.
func (aetu *AppEmailTemplateUpdate) Mutation() *AppEmailTemplateMutation {
	return aetu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (aetu *AppEmailTemplateUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if err := aetu.defaults(); err != nil {
		return 0, err
	}
	if len(aetu.hooks) == 0 {
		if err = aetu.check(); err != nil {
			return 0, err
		}
		affected, err = aetu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AppEmailTemplateMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = aetu.check(); err != nil {
				return 0, err
			}
			aetu.mutation = mutation
			affected, err = aetu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(aetu.hooks) - 1; i >= 0; i-- {
			if aetu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = aetu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, aetu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (aetu *AppEmailTemplateUpdate) SaveX(ctx context.Context) int {
	affected, err := aetu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (aetu *AppEmailTemplateUpdate) Exec(ctx context.Context) error {
	_, err := aetu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aetu *AppEmailTemplateUpdate) ExecX(ctx context.Context) {
	if err := aetu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (aetu *AppEmailTemplateUpdate) defaults() error {
	if _, ok := aetu.mutation.UpdatedAt(); !ok {
		if appemailtemplate.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized appemailtemplate.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := appemailtemplate.UpdateDefaultUpdatedAt()
		aetu.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (aetu *AppEmailTemplateUpdate) check() error {
	if v, ok := aetu.mutation.Body(); ok {
		if err := appemailtemplate.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "AppEmailTemplate.body": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (aetu *AppEmailTemplateUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AppEmailTemplateUpdate {
	aetu.modifiers = append(aetu.modifiers, modifiers...)
	return aetu
}

func (aetu *AppEmailTemplateUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   appemailtemplate.Table,
			Columns: appemailtemplate.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: appemailtemplate.FieldID,
			},
		},
	}
	if ps := aetu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aetu.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appemailtemplate.FieldCreatedAt,
		})
	}
	if value, ok := aetu.mutation.AddedCreatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appemailtemplate.FieldCreatedAt,
		})
	}
	if value, ok := aetu.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appemailtemplate.FieldUpdatedAt,
		})
	}
	if value, ok := aetu.mutation.AddedUpdatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appemailtemplate.FieldUpdatedAt,
		})
	}
	if value, ok := aetu.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appemailtemplate.FieldDeletedAt,
		})
	}
	if value, ok := aetu.mutation.AddedDeletedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appemailtemplate.FieldDeletedAt,
		})
	}
	if value, ok := aetu.mutation.AppID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: appemailtemplate.FieldAppID,
		})
	}
	if value, ok := aetu.mutation.LangID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: appemailtemplate.FieldLangID,
		})
	}
	if value, ok := aetu.mutation.DefaultToUsername(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: appemailtemplate.FieldDefaultToUsername,
		})
	}
	if value, ok := aetu.mutation.UsedFor(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: appemailtemplate.FieldUsedFor,
		})
	}
	if value, ok := aetu.mutation.Sender(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: appemailtemplate.FieldSender,
		})
	}
	if value, ok := aetu.mutation.ReplyTos(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: appemailtemplate.FieldReplyTos,
		})
	}
	if value, ok := aetu.mutation.CcTos(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: appemailtemplate.FieldCcTos,
		})
	}
	if value, ok := aetu.mutation.Subject(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: appemailtemplate.FieldSubject,
		})
	}
	if value, ok := aetu.mutation.Body(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: appemailtemplate.FieldBody,
		})
	}
	_spec.Modifiers = aetu.modifiers
	if n, err = sqlgraph.UpdateNodes(ctx, aetu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appemailtemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// AppEmailTemplateUpdateOne is the builder for updating a single AppEmailTemplate entity.
type AppEmailTemplateUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *AppEmailTemplateMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreatedAt sets the "created_at" field.
func (aetuo *AppEmailTemplateUpdateOne) SetCreatedAt(u uint32) *AppEmailTemplateUpdateOne {
	aetuo.mutation.ResetCreatedAt()
	aetuo.mutation.SetCreatedAt(u)
	return aetuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (aetuo *AppEmailTemplateUpdateOne) SetNillableCreatedAt(u *uint32) *AppEmailTemplateUpdateOne {
	if u != nil {
		aetuo.SetCreatedAt(*u)
	}
	return aetuo
}

// AddCreatedAt adds u to the "created_at" field.
func (aetuo *AppEmailTemplateUpdateOne) AddCreatedAt(u int32) *AppEmailTemplateUpdateOne {
	aetuo.mutation.AddCreatedAt(u)
	return aetuo
}

// SetUpdatedAt sets the "updated_at" field.
func (aetuo *AppEmailTemplateUpdateOne) SetUpdatedAt(u uint32) *AppEmailTemplateUpdateOne {
	aetuo.mutation.ResetUpdatedAt()
	aetuo.mutation.SetUpdatedAt(u)
	return aetuo
}

// AddUpdatedAt adds u to the "updated_at" field.
func (aetuo *AppEmailTemplateUpdateOne) AddUpdatedAt(u int32) *AppEmailTemplateUpdateOne {
	aetuo.mutation.AddUpdatedAt(u)
	return aetuo
}

// SetDeletedAt sets the "deleted_at" field.
func (aetuo *AppEmailTemplateUpdateOne) SetDeletedAt(u uint32) *AppEmailTemplateUpdateOne {
	aetuo.mutation.ResetDeletedAt()
	aetuo.mutation.SetDeletedAt(u)
	return aetuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (aetuo *AppEmailTemplateUpdateOne) SetNillableDeletedAt(u *uint32) *AppEmailTemplateUpdateOne {
	if u != nil {
		aetuo.SetDeletedAt(*u)
	}
	return aetuo
}

// AddDeletedAt adds u to the "deleted_at" field.
func (aetuo *AppEmailTemplateUpdateOne) AddDeletedAt(u int32) *AppEmailTemplateUpdateOne {
	aetuo.mutation.AddDeletedAt(u)
	return aetuo
}

// SetAppID sets the "app_id" field.
func (aetuo *AppEmailTemplateUpdateOne) SetAppID(u uuid.UUID) *AppEmailTemplateUpdateOne {
	aetuo.mutation.SetAppID(u)
	return aetuo
}

// SetLangID sets the "lang_id" field.
func (aetuo *AppEmailTemplateUpdateOne) SetLangID(u uuid.UUID) *AppEmailTemplateUpdateOne {
	aetuo.mutation.SetLangID(u)
	return aetuo
}

// SetDefaultToUsername sets the "default_to_username" field.
func (aetuo *AppEmailTemplateUpdateOne) SetDefaultToUsername(s string) *AppEmailTemplateUpdateOne {
	aetuo.mutation.SetDefaultToUsername(s)
	return aetuo
}

// SetUsedFor sets the "used_for" field.
func (aetuo *AppEmailTemplateUpdateOne) SetUsedFor(s string) *AppEmailTemplateUpdateOne {
	aetuo.mutation.SetUsedFor(s)
	return aetuo
}

// SetSender sets the "sender" field.
func (aetuo *AppEmailTemplateUpdateOne) SetSender(s string) *AppEmailTemplateUpdateOne {
	aetuo.mutation.SetSender(s)
	return aetuo
}

// SetReplyTos sets the "reply_tos" field.
func (aetuo *AppEmailTemplateUpdateOne) SetReplyTos(s []string) *AppEmailTemplateUpdateOne {
	aetuo.mutation.SetReplyTos(s)
	return aetuo
}

// SetCcTos sets the "cc_tos" field.
func (aetuo *AppEmailTemplateUpdateOne) SetCcTos(s []string) *AppEmailTemplateUpdateOne {
	aetuo.mutation.SetCcTos(s)
	return aetuo
}

// SetSubject sets the "subject" field.
func (aetuo *AppEmailTemplateUpdateOne) SetSubject(s string) *AppEmailTemplateUpdateOne {
	aetuo.mutation.SetSubject(s)
	return aetuo
}

// SetBody sets the "body" field.
func (aetuo *AppEmailTemplateUpdateOne) SetBody(s string) *AppEmailTemplateUpdateOne {
	aetuo.mutation.SetBody(s)
	return aetuo
}

// Mutation returns the AppEmailTemplateMutation object of the builder.
func (aetuo *AppEmailTemplateUpdateOne) Mutation() *AppEmailTemplateMutation {
	return aetuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (aetuo *AppEmailTemplateUpdateOne) Select(field string, fields ...string) *AppEmailTemplateUpdateOne {
	aetuo.fields = append([]string{field}, fields...)
	return aetuo
}

// Save executes the query and returns the updated AppEmailTemplate entity.
func (aetuo *AppEmailTemplateUpdateOne) Save(ctx context.Context) (*AppEmailTemplate, error) {
	var (
		err  error
		node *AppEmailTemplate
	)
	if err := aetuo.defaults(); err != nil {
		return nil, err
	}
	if len(aetuo.hooks) == 0 {
		if err = aetuo.check(); err != nil {
			return nil, err
		}
		node, err = aetuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AppEmailTemplateMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = aetuo.check(); err != nil {
				return nil, err
			}
			aetuo.mutation = mutation
			node, err = aetuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(aetuo.hooks) - 1; i >= 0; i-- {
			if aetuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = aetuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, aetuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*AppEmailTemplate)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from AppEmailTemplateMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (aetuo *AppEmailTemplateUpdateOne) SaveX(ctx context.Context) *AppEmailTemplate {
	node, err := aetuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (aetuo *AppEmailTemplateUpdateOne) Exec(ctx context.Context) error {
	_, err := aetuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aetuo *AppEmailTemplateUpdateOne) ExecX(ctx context.Context) {
	if err := aetuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (aetuo *AppEmailTemplateUpdateOne) defaults() error {
	if _, ok := aetuo.mutation.UpdatedAt(); !ok {
		if appemailtemplate.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized appemailtemplate.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := appemailtemplate.UpdateDefaultUpdatedAt()
		aetuo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (aetuo *AppEmailTemplateUpdateOne) check() error {
	if v, ok := aetuo.mutation.Body(); ok {
		if err := appemailtemplate.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "AppEmailTemplate.body": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (aetuo *AppEmailTemplateUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AppEmailTemplateUpdateOne {
	aetuo.modifiers = append(aetuo.modifiers, modifiers...)
	return aetuo
}

func (aetuo *AppEmailTemplateUpdateOne) sqlSave(ctx context.Context) (_node *AppEmailTemplate, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   appemailtemplate.Table,
			Columns: appemailtemplate.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: appemailtemplate.FieldID,
			},
		},
	}
	id, ok := aetuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AppEmailTemplate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := aetuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, appemailtemplate.FieldID)
		for _, f := range fields {
			if !appemailtemplate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != appemailtemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := aetuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aetuo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appemailtemplate.FieldCreatedAt,
		})
	}
	if value, ok := aetuo.mutation.AddedCreatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appemailtemplate.FieldCreatedAt,
		})
	}
	if value, ok := aetuo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appemailtemplate.FieldUpdatedAt,
		})
	}
	if value, ok := aetuo.mutation.AddedUpdatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appemailtemplate.FieldUpdatedAt,
		})
	}
	if value, ok := aetuo.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appemailtemplate.FieldDeletedAt,
		})
	}
	if value, ok := aetuo.mutation.AddedDeletedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appemailtemplate.FieldDeletedAt,
		})
	}
	if value, ok := aetuo.mutation.AppID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: appemailtemplate.FieldAppID,
		})
	}
	if value, ok := aetuo.mutation.LangID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: appemailtemplate.FieldLangID,
		})
	}
	if value, ok := aetuo.mutation.DefaultToUsername(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: appemailtemplate.FieldDefaultToUsername,
		})
	}
	if value, ok := aetuo.mutation.UsedFor(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: appemailtemplate.FieldUsedFor,
		})
	}
	if value, ok := aetuo.mutation.Sender(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: appemailtemplate.FieldSender,
		})
	}
	if value, ok := aetuo.mutation.ReplyTos(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: appemailtemplate.FieldReplyTos,
		})
	}
	if value, ok := aetuo.mutation.CcTos(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: appemailtemplate.FieldCcTos,
		})
	}
	if value, ok := aetuo.mutation.Subject(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: appemailtemplate.FieldSubject,
		})
	}
	if value, ok := aetuo.mutation.Body(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: appemailtemplate.FieldBody,
		})
	}
	_spec.Modifiers = aetuo.modifiers
	_node = &AppEmailTemplate{config: aetuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, aetuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appemailtemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
