// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"

	"github.com/NpoolPlatform/third-manager/pkg/db/ent/migrate"
	"github.com/google/uuid"

	"github.com/NpoolPlatform/third-manager/pkg/db/ent/appcontact"
	"github.com/NpoolPlatform/third-manager/pkg/db/ent/appemailtemplate"
	"github.com/NpoolPlatform/third-manager/pkg/db/ent/appsmstemplate"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AppContact is the client for interacting with the AppContact builders.
	AppContact *AppContactClient
	// AppEmailTemplate is the client for interacting with the AppEmailTemplate builders.
	AppEmailTemplate *AppEmailTemplateClient
	// AppSMSTemplate is the client for interacting with the AppSMSTemplate builders.
	AppSMSTemplate *AppSMSTemplateClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AppContact = NewAppContactClient(c.config)
	c.AppEmailTemplate = NewAppEmailTemplateClient(c.config)
	c.AppSMSTemplate = NewAppSMSTemplateClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		AppContact:       NewAppContactClient(cfg),
		AppEmailTemplate: NewAppEmailTemplateClient(cfg),
		AppSMSTemplate:   NewAppSMSTemplateClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		AppContact:       NewAppContactClient(cfg),
		AppEmailTemplate: NewAppEmailTemplateClient(cfg),
		AppSMSTemplate:   NewAppSMSTemplateClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AppContact.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.AppContact.Use(hooks...)
	c.AppEmailTemplate.Use(hooks...)
	c.AppSMSTemplate.Use(hooks...)
}

// AppContactClient is a client for the AppContact schema.
type AppContactClient struct {
	config
}

// NewAppContactClient returns a client for the AppContact from the given config.
func NewAppContactClient(c config) *AppContactClient {
	return &AppContactClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `appcontact.Hooks(f(g(h())))`.
func (c *AppContactClient) Use(hooks ...Hook) {
	c.hooks.AppContact = append(c.hooks.AppContact, hooks...)
}

// Create returns a builder for creating a AppContact entity.
func (c *AppContactClient) Create() *AppContactCreate {
	mutation := newAppContactMutation(c.config, OpCreate)
	return &AppContactCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AppContact entities.
func (c *AppContactClient) CreateBulk(builders ...*AppContactCreate) *AppContactCreateBulk {
	return &AppContactCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AppContact.
func (c *AppContactClient) Update() *AppContactUpdate {
	mutation := newAppContactMutation(c.config, OpUpdate)
	return &AppContactUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AppContactClient) UpdateOne(ac *AppContact) *AppContactUpdateOne {
	mutation := newAppContactMutation(c.config, OpUpdateOne, withAppContact(ac))
	return &AppContactUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AppContactClient) UpdateOneID(id uuid.UUID) *AppContactUpdateOne {
	mutation := newAppContactMutation(c.config, OpUpdateOne, withAppContactID(id))
	return &AppContactUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AppContact.
func (c *AppContactClient) Delete() *AppContactDelete {
	mutation := newAppContactMutation(c.config, OpDelete)
	return &AppContactDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AppContactClient) DeleteOne(ac *AppContact) *AppContactDeleteOne {
	return c.DeleteOneID(ac.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *AppContactClient) DeleteOneID(id uuid.UUID) *AppContactDeleteOne {
	builder := c.Delete().Where(appcontact.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AppContactDeleteOne{builder}
}

// Query returns a query builder for AppContact.
func (c *AppContactClient) Query() *AppContactQuery {
	return &AppContactQuery{
		config: c.config,
	}
}

// Get returns a AppContact entity by its id.
func (c *AppContactClient) Get(ctx context.Context, id uuid.UUID) (*AppContact, error) {
	return c.Query().Where(appcontact.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AppContactClient) GetX(ctx context.Context, id uuid.UUID) *AppContact {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AppContactClient) Hooks() []Hook {
	hooks := c.hooks.AppContact
	return append(hooks[:len(hooks):len(hooks)], appcontact.Hooks[:]...)
}

// AppEmailTemplateClient is a client for the AppEmailTemplate schema.
type AppEmailTemplateClient struct {
	config
}

// NewAppEmailTemplateClient returns a client for the AppEmailTemplate from the given config.
func NewAppEmailTemplateClient(c config) *AppEmailTemplateClient {
	return &AppEmailTemplateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `appemailtemplate.Hooks(f(g(h())))`.
func (c *AppEmailTemplateClient) Use(hooks ...Hook) {
	c.hooks.AppEmailTemplate = append(c.hooks.AppEmailTemplate, hooks...)
}

// Create returns a builder for creating a AppEmailTemplate entity.
func (c *AppEmailTemplateClient) Create() *AppEmailTemplateCreate {
	mutation := newAppEmailTemplateMutation(c.config, OpCreate)
	return &AppEmailTemplateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AppEmailTemplate entities.
func (c *AppEmailTemplateClient) CreateBulk(builders ...*AppEmailTemplateCreate) *AppEmailTemplateCreateBulk {
	return &AppEmailTemplateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AppEmailTemplate.
func (c *AppEmailTemplateClient) Update() *AppEmailTemplateUpdate {
	mutation := newAppEmailTemplateMutation(c.config, OpUpdate)
	return &AppEmailTemplateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AppEmailTemplateClient) UpdateOne(aet *AppEmailTemplate) *AppEmailTemplateUpdateOne {
	mutation := newAppEmailTemplateMutation(c.config, OpUpdateOne, withAppEmailTemplate(aet))
	return &AppEmailTemplateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AppEmailTemplateClient) UpdateOneID(id uuid.UUID) *AppEmailTemplateUpdateOne {
	mutation := newAppEmailTemplateMutation(c.config, OpUpdateOne, withAppEmailTemplateID(id))
	return &AppEmailTemplateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AppEmailTemplate.
func (c *AppEmailTemplateClient) Delete() *AppEmailTemplateDelete {
	mutation := newAppEmailTemplateMutation(c.config, OpDelete)
	return &AppEmailTemplateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AppEmailTemplateClient) DeleteOne(aet *AppEmailTemplate) *AppEmailTemplateDeleteOne {
	return c.DeleteOneID(aet.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *AppEmailTemplateClient) DeleteOneID(id uuid.UUID) *AppEmailTemplateDeleteOne {
	builder := c.Delete().Where(appemailtemplate.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AppEmailTemplateDeleteOne{builder}
}

// Query returns a query builder for AppEmailTemplate.
func (c *AppEmailTemplateClient) Query() *AppEmailTemplateQuery {
	return &AppEmailTemplateQuery{
		config: c.config,
	}
}

// Get returns a AppEmailTemplate entity by its id.
func (c *AppEmailTemplateClient) Get(ctx context.Context, id uuid.UUID) (*AppEmailTemplate, error) {
	return c.Query().Where(appemailtemplate.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AppEmailTemplateClient) GetX(ctx context.Context, id uuid.UUID) *AppEmailTemplate {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AppEmailTemplateClient) Hooks() []Hook {
	return c.hooks.AppEmailTemplate
}

// AppSMSTemplateClient is a client for the AppSMSTemplate schema.
type AppSMSTemplateClient struct {
	config
}

// NewAppSMSTemplateClient returns a client for the AppSMSTemplate from the given config.
func NewAppSMSTemplateClient(c config) *AppSMSTemplateClient {
	return &AppSMSTemplateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `appsmstemplate.Hooks(f(g(h())))`.
func (c *AppSMSTemplateClient) Use(hooks ...Hook) {
	c.hooks.AppSMSTemplate = append(c.hooks.AppSMSTemplate, hooks...)
}

// Create returns a builder for creating a AppSMSTemplate entity.
func (c *AppSMSTemplateClient) Create() *AppSMSTemplateCreate {
	mutation := newAppSMSTemplateMutation(c.config, OpCreate)
	return &AppSMSTemplateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AppSMSTemplate entities.
func (c *AppSMSTemplateClient) CreateBulk(builders ...*AppSMSTemplateCreate) *AppSMSTemplateCreateBulk {
	return &AppSMSTemplateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AppSMSTemplate.
func (c *AppSMSTemplateClient) Update() *AppSMSTemplateUpdate {
	mutation := newAppSMSTemplateMutation(c.config, OpUpdate)
	return &AppSMSTemplateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AppSMSTemplateClient) UpdateOne(ast *AppSMSTemplate) *AppSMSTemplateUpdateOne {
	mutation := newAppSMSTemplateMutation(c.config, OpUpdateOne, withAppSMSTemplate(ast))
	return &AppSMSTemplateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AppSMSTemplateClient) UpdateOneID(id uuid.UUID) *AppSMSTemplateUpdateOne {
	mutation := newAppSMSTemplateMutation(c.config, OpUpdateOne, withAppSMSTemplateID(id))
	return &AppSMSTemplateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AppSMSTemplate.
func (c *AppSMSTemplateClient) Delete() *AppSMSTemplateDelete {
	mutation := newAppSMSTemplateMutation(c.config, OpDelete)
	return &AppSMSTemplateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AppSMSTemplateClient) DeleteOne(ast *AppSMSTemplate) *AppSMSTemplateDeleteOne {
	return c.DeleteOneID(ast.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *AppSMSTemplateClient) DeleteOneID(id uuid.UUID) *AppSMSTemplateDeleteOne {
	builder := c.Delete().Where(appsmstemplate.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AppSMSTemplateDeleteOne{builder}
}

// Query returns a query builder for AppSMSTemplate.
func (c *AppSMSTemplateClient) Query() *AppSMSTemplateQuery {
	return &AppSMSTemplateQuery{
		config: c.config,
	}
}

// Get returns a AppSMSTemplate entity by its id.
func (c *AppSMSTemplateClient) Get(ctx context.Context, id uuid.UUID) (*AppSMSTemplate, error) {
	return c.Query().Where(appsmstemplate.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AppSMSTemplateClient) GetX(ctx context.Context, id uuid.UUID) *AppSMSTemplate {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AppSMSTemplateClient) Hooks() []Hook {
	return c.hooks.AppSMSTemplate
}
