// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/third-manager/pkg/db/ent/notiftemplate"
	"github.com/NpoolPlatform/third-manager/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// NotifTemplateQuery is the builder for querying NotifTemplate entities.
type NotifTemplateQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.NotifTemplate
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the NotifTemplateQuery builder.
func (ntq *NotifTemplateQuery) Where(ps ...predicate.NotifTemplate) *NotifTemplateQuery {
	ntq.predicates = append(ntq.predicates, ps...)
	return ntq
}

// Limit adds a limit step to the query.
func (ntq *NotifTemplateQuery) Limit(limit int) *NotifTemplateQuery {
	ntq.limit = &limit
	return ntq
}

// Offset adds an offset step to the query.
func (ntq *NotifTemplateQuery) Offset(offset int) *NotifTemplateQuery {
	ntq.offset = &offset
	return ntq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ntq *NotifTemplateQuery) Unique(unique bool) *NotifTemplateQuery {
	ntq.unique = &unique
	return ntq
}

// Order adds an order step to the query.
func (ntq *NotifTemplateQuery) Order(o ...OrderFunc) *NotifTemplateQuery {
	ntq.order = append(ntq.order, o...)
	return ntq
}

// First returns the first NotifTemplate entity from the query.
// Returns a *NotFoundError when no NotifTemplate was found.
func (ntq *NotifTemplateQuery) First(ctx context.Context) (*NotifTemplate, error) {
	nodes, err := ntq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{notiftemplate.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ntq *NotifTemplateQuery) FirstX(ctx context.Context) *NotifTemplate {
	node, err := ntq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first NotifTemplate ID from the query.
// Returns a *NotFoundError when no NotifTemplate ID was found.
func (ntq *NotifTemplateQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ntq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{notiftemplate.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ntq *NotifTemplateQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := ntq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single NotifTemplate entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one NotifTemplate entity is found.
// Returns a *NotFoundError when no NotifTemplate entities are found.
func (ntq *NotifTemplateQuery) Only(ctx context.Context) (*NotifTemplate, error) {
	nodes, err := ntq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{notiftemplate.Label}
	default:
		return nil, &NotSingularError{notiftemplate.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ntq *NotifTemplateQuery) OnlyX(ctx context.Context) *NotifTemplate {
	node, err := ntq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only NotifTemplate ID in the query.
// Returns a *NotSingularError when more than one NotifTemplate ID is found.
// Returns a *NotFoundError when no entities are found.
func (ntq *NotifTemplateQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ntq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{notiftemplate.Label}
	default:
		err = &NotSingularError{notiftemplate.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ntq *NotifTemplateQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := ntq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of NotifTemplates.
func (ntq *NotifTemplateQuery) All(ctx context.Context) ([]*NotifTemplate, error) {
	if err := ntq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ntq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ntq *NotifTemplateQuery) AllX(ctx context.Context) []*NotifTemplate {
	nodes, err := ntq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of NotifTemplate IDs.
func (ntq *NotifTemplateQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := ntq.Select(notiftemplate.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ntq *NotifTemplateQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := ntq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ntq *NotifTemplateQuery) Count(ctx context.Context) (int, error) {
	if err := ntq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ntq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ntq *NotifTemplateQuery) CountX(ctx context.Context) int {
	count, err := ntq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ntq *NotifTemplateQuery) Exist(ctx context.Context) (bool, error) {
	if err := ntq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ntq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ntq *NotifTemplateQuery) ExistX(ctx context.Context) bool {
	exist, err := ntq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the NotifTemplateQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ntq *NotifTemplateQuery) Clone() *NotifTemplateQuery {
	if ntq == nil {
		return nil
	}
	return &NotifTemplateQuery{
		config:     ntq.config,
		limit:      ntq.limit,
		offset:     ntq.offset,
		order:      append([]OrderFunc{}, ntq.order...),
		predicates: append([]predicate.NotifTemplate{}, ntq.predicates...),
		// clone intermediate query.
		sql:    ntq.sql.Clone(),
		path:   ntq.path,
		unique: ntq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.NotifTemplate.Query().
//		GroupBy(notiftemplate.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (ntq *NotifTemplateQuery) GroupBy(field string, fields ...string) *NotifTemplateGroupBy {
	grbuild := &NotifTemplateGroupBy{config: ntq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ntq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ntq.sqlQuery(ctx), nil
	}
	grbuild.label = notiftemplate.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.NotifTemplate.Query().
//		Select(notiftemplate.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (ntq *NotifTemplateQuery) Select(fields ...string) *NotifTemplateSelect {
	ntq.fields = append(ntq.fields, fields...)
	selbuild := &NotifTemplateSelect{NotifTemplateQuery: ntq}
	selbuild.label = notiftemplate.Label
	selbuild.flds, selbuild.scan = &ntq.fields, selbuild.Scan
	return selbuild
}

func (ntq *NotifTemplateQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ntq.fields {
		if !notiftemplate.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ntq.path != nil {
		prev, err := ntq.path(ctx)
		if err != nil {
			return err
		}
		ntq.sql = prev
	}
	if notiftemplate.Policy == nil {
		return errors.New("ent: uninitialized notiftemplate.Policy (forgotten import ent/runtime?)")
	}
	if err := notiftemplate.Policy.EvalQuery(ctx, ntq); err != nil {
		return err
	}
	return nil
}

func (ntq *NotifTemplateQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*NotifTemplate, error) {
	var (
		nodes = []*NotifTemplate{}
		_spec = ntq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*NotifTemplate).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &NotifTemplate{config: ntq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(ntq.modifiers) > 0 {
		_spec.Modifiers = ntq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ntq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ntq *NotifTemplateQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ntq.querySpec()
	if len(ntq.modifiers) > 0 {
		_spec.Modifiers = ntq.modifiers
	}
	_spec.Node.Columns = ntq.fields
	if len(ntq.fields) > 0 {
		_spec.Unique = ntq.unique != nil && *ntq.unique
	}
	return sqlgraph.CountNodes(ctx, ntq.driver, _spec)
}

func (ntq *NotifTemplateQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ntq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (ntq *NotifTemplateQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   notiftemplate.Table,
			Columns: notiftemplate.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: notiftemplate.FieldID,
			},
		},
		From:   ntq.sql,
		Unique: true,
	}
	if unique := ntq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ntq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notiftemplate.FieldID)
		for i := range fields {
			if fields[i] != notiftemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ntq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ntq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ntq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ntq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ntq *NotifTemplateQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ntq.driver.Dialect())
	t1 := builder.Table(notiftemplate.Table)
	columns := ntq.fields
	if len(columns) == 0 {
		columns = notiftemplate.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ntq.sql != nil {
		selector = ntq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ntq.unique != nil && *ntq.unique {
		selector.Distinct()
	}
	for _, m := range ntq.modifiers {
		m(selector)
	}
	for _, p := range ntq.predicates {
		p(selector)
	}
	for _, p := range ntq.order {
		p(selector)
	}
	if offset := ntq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ntq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (ntq *NotifTemplateQuery) ForUpdate(opts ...sql.LockOption) *NotifTemplateQuery {
	if ntq.driver.Dialect() == dialect.Postgres {
		ntq.Unique(false)
	}
	ntq.modifiers = append(ntq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return ntq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (ntq *NotifTemplateQuery) ForShare(opts ...sql.LockOption) *NotifTemplateQuery {
	if ntq.driver.Dialect() == dialect.Postgres {
		ntq.Unique(false)
	}
	ntq.modifiers = append(ntq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return ntq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ntq *NotifTemplateQuery) Modify(modifiers ...func(s *sql.Selector)) *NotifTemplateSelect {
	ntq.modifiers = append(ntq.modifiers, modifiers...)
	return ntq.Select()
}

// NotifTemplateGroupBy is the group-by builder for NotifTemplate entities.
type NotifTemplateGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ntgb *NotifTemplateGroupBy) Aggregate(fns ...AggregateFunc) *NotifTemplateGroupBy {
	ntgb.fns = append(ntgb.fns, fns...)
	return ntgb
}

// Scan applies the group-by query and scans the result into the given value.
func (ntgb *NotifTemplateGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := ntgb.path(ctx)
	if err != nil {
		return err
	}
	ntgb.sql = query
	return ntgb.sqlScan(ctx, v)
}

func (ntgb *NotifTemplateGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range ntgb.fields {
		if !notiftemplate.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ntgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ntgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ntgb *NotifTemplateGroupBy) sqlQuery() *sql.Selector {
	selector := ntgb.sql.Select()
	aggregation := make([]string, 0, len(ntgb.fns))
	for _, fn := range ntgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(ntgb.fields)+len(ntgb.fns))
		for _, f := range ntgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(ntgb.fields...)...)
}

// NotifTemplateSelect is the builder for selecting fields of NotifTemplate entities.
type NotifTemplateSelect struct {
	*NotifTemplateQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (nts *NotifTemplateSelect) Scan(ctx context.Context, v interface{}) error {
	if err := nts.prepareQuery(ctx); err != nil {
		return err
	}
	nts.sql = nts.NotifTemplateQuery.sqlQuery(ctx)
	return nts.sqlScan(ctx, v)
}

func (nts *NotifTemplateSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := nts.sql.Query()
	if err := nts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (nts *NotifTemplateSelect) Modify(modifiers ...func(s *sql.Selector)) *NotifTemplateSelect {
	nts.modifiers = append(nts.modifiers, modifiers...)
	return nts
}
