// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AppContact is the predicate function for appcontact builders.
type AppContact func(*sql.Selector)

// AppEmailTemplate is the predicate function for appemailtemplate builders.
type AppEmailTemplate func(*sql.Selector)

// AppSMSTemplate is the predicate function for appsmstemplate builders.
type AppSMSTemplate func(*sql.Selector)
